// Generated by CoffeeScript 1.7.1
var Thenjs, fs;

Thenjs = require('./then.js');

fs = require('fs');

Thenjs(function(cont) {
  return cont();
}).each([1, 2, 3], function(cont, num) {
  console.log("***" + num);
  return cont(null, 2 * num);
}, false).then((function(cont, result) {
  console.log(result);
  return cont(null, "hello, world");
}))["finally"](function(cont, error, result) {
  return console.log(result);
});

Thenjs(function(cont) {
  return cont();
}).then(function(cont) {
  cont(null, 9);
  // return;
  cont(null, 8);
})["finally"]((function(cont, error, result) {
  return console.log(result);
}));
